on:
    pull_request:
    push:
        branches:
            -   main

permissions:
    contents: read

name: Build
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
                    cache: yarn
            -   name: Install deps
                run: yarn install --frozen-lockfile
            -   name: Type Check
                run: yarn type-check
            -   name: Format Check
                run: yarn format-check
            -   name: Lint
                run: yarn lint