on:
    push:
        tags:
            - "v*"

permissions: write-all

name: Release
jobs:
    release:
        name: Release GitHub Actions
        runs-on: ubuntu-latest
        steps:
            -   uses: technote-space/release-github-actions@v6
                with:
                    BUILD_COMMAND: yarn all